database:
    schema: pattern-jwt
    url: jdbc:mysql://localhost:3306
    username: root
    password: 
    encrypted: false
    driver: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQLDialect
    ddl: validate 
    migrations: classpath:db/migration
  