spring.datasource.url: jdbc:mysql://localhost:3306/tokamak?useSSL=false&requireSSL=false
spring.datasource.username: root
spring.datasource.password: 

spring.jpa.open-in-view: false
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

flyway.schemas: tokamak
flyway.locations: classpath:db/migration
flyway.user: root
flyway.password: 
flyway.url: jdbc:mysql://localhost:3306?useSSL=false&requireSSL=false
