zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    accounts:
      path: /v1/accounts/**
      url: http://localhost:9600/v1/accounts
    audiences:
      path: /v1/audiences/**
      url: http://localhost:9600/v1/audiences
    authorities:
      path: /v1/authorities/**
      url: http://localhost:9600/v1/authorities
    clients:
      path: /v1/clients/**
      url: http://localhost:9600/v1/clients      
    policies:
      path: /v1/policies/**
      url: http://localhost:9600/v1/policies      
    roles:
      path: /v1/roles/**
      url: http://localhost:9600/v1/roles
    scopes:
      path: /v1/scopes/**
      url: http://localhost:9600/v1/scopes            
    grant_types:
      path: /v1/grant_types/**
      url: http://localhost:9600/v1/grant_types 
      
ribbon.eureka.enabled: false

spring:
  redis:
    host: localhost
    port: 6379
    timeout: 10
    pool:
      max-active: 10
      max-idle: 10
      min-idle: 0
      max-wait: 60000

server.port: 9605
management.port: 9606

management.context-path: /manage
management.address: 127.0.0.1

endpoints.enabled: true
endpoints.info.enabled: true
endpoints.shutdown.enabled: true
endpoints.metrics.enabled: true
endpoints.health.enabled: true